project:
  env: "DEV"

server:
  host: "127.0.0.1"
  port: 8004

proxy:
  domain_mappings:
    "grok.superlang.top": "api.x.ai"
    "chatgpt.superlang.top": "api.openai.com"
    "test.superlang.top": "api.x.ai"
  default_domain: "api.x.ai"
  default_scheme: "https"  #

log:
  level: "debug"
  filepath: "log"
  filename: "chat_proxy"

database:    
  mysql:
    host: "192.168.3.100"
    port: 49154
    username: "root"
    password: "admin"
    db_name: "chat_rabbit"
  redis:
    address: "192.168.3.100:49155"
    password: ""
    db_option: 6
    prefix: "p"
    max_idle: 200
    pool_size: 64
    max_retries: 3
    idle_timeout: 0

