// Code generated by "stringer -type ErrCode -linecomment"; DO NOT EDIT.

package apperrors

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OK-0]
	_ = x[UserNotFound-1001]
}

const (
	_ErrCode_name_0 = "OK"
	_ErrCode_name_1 = "用户不存在"
)

func (i ErrCode) String() string {
	switch {
	case i == 0:
		return _ErrCode_name_0
	case i == 1001:
		return _ErrCode_name_1
	default:
		return "ErrCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
